name: homebrew-store-cdn

services:
  homebrew-store-cdn:
    image: fabiocdo/homebrew-store-cdn:latest
    container_name: homebrew-store-cdn
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./settings.env
    volumes:
      - ./data:/data
      - ./nginx.conf:/app/nginx.conf:ro
      - ./nginx.http.conf:/app/nginx.http.conf:ro
      - ./certs:/etc/nginx/certs
    restart: unless-stopped
