services:
  homebrew-cdn-m1-server:
    build: .
    image: fabiocdo/homebrew-cdn-m1-server:latest
    container_name: homebrew-cdn-m1-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    restart: unless-stopped
